export const Gujarat = [
    "Abrama",
    "Adalaj",
    "Ahmadabad",
    "Ahwa",
    "Amod",
    "Amreli",
    "Amroli",
    "Anand",
    "Anjar",
    "Ankleshwar",
    "Babra",
    "Bagasara",
    "Bagasra",
    "Banas Kantha",
    "Bantva",
    "Bardoli",
    "Bedi",
    "Bhachau",
    "Bhanvad",
    "Bharuch",
    "Bhavnagar",
    "Bhayavadar",
    "Bhuj",
    "Bilimora",
    "Bilkha",
    "Borsad",
    "Botad",
    "Chaklasi",
    "Chalala",
    "Chanasma",
    "Chhala",
    "Chhota Udepur",
    "Chikhli",
    "Chotila",
    "Dabhoi",
    "Dahegam",
    "Dahod",
    "Dakor",
    "Damnagar",
    "Dangs (India)",
    "Dayapar",
    "Delvada",
    "Delwada",
    "Devbhumi Dwarka",
    "Devgadh Bariya",
    "Dhandhuka",
    "Dhanera",
    "Dharampur",
    "Dhari",
    "Dhola",
    "Dholka",
    "Dhoraji",
    "Dhrangadhra",
    "Dhrol",
    "Dhuwaran",
    "Disa",
    "Dohad",
    "Dungarpur",
    "Dwarka",
    "Gadhada",
    "Gandevi",
    "Gandhidham",
    "Gandhinagar",
    "Gariadhar",
    "Ghogha",
    "Gir Somnath",
    "Godhra",
    "Gondal",
    "Halol",
    "Halvad",
    "Hansot",
    "Harij",
    "Himatnagar",
    "Jalalpore",
    "Jalalpur",
    "Jambusar",
    "Jamnagar",
    "Jasdan",
    "Jetalsar",
    "Jetpur",
    "Jhulasan",
    "Jodhpur",
    "Jodia",
    "Jodiya Bandar",
    "Junagadh",
    "Kachchh",
    "Kadi",
    "Kadod",
    "Kalavad",
    "Kalol",
    "Kandla",
    "Kanodar",
    "Kapadvanj",
    "Karamsad",
    "Kathor",
    "Katpur",
    "Kavant",
    "Kawant",
    "Keshod",
    "Khambhalia",
    "Khambhaliya",
    "Khambhat",
    "Kheda",
    "Khedbrahma",
    "Kheralu",
    "Kodinar",
    "Kosamba",
    "Kundla",
    "Kutch district",
    "Kutiyana",
    "Lakhtar",
    "Lalpur",
    "Lathi",
    "Limbdi",
    "Lunavada",
    "Mahemdavad",
    "Mahesana",
    "Mahudha",
    "Malpur",
    "Manavadar",
    "Mandal",
    "Mandvi",
    "Mandvi (Surat)",
    "Mangrol",
    "Mansa",
    "Meghraj",
    "Mehsana",
    "Mendarda",
    "Modasa",
    "Morbi",
    "Morva (Hadaf)",
    "Morwa",
    "Mundra",
    "Nadiad",
    "Naliya",
    "Narmada",
    "Naroda",
    "Navsari",
    "Okha",
    "Olpad",
    "Paddhari",
    "Padra",
    "Palanpur",
    "Palitana",
    "Paliyad",
    "Panch Mahals",
    "Panchmahal district",
    "Pardi",
    "Parnera",
    "Patan",
    "Pavi Jetpur",
    "Petlad",
    "Porbandar",
    "Radhanpur",
    "Rajkot",
    "Rajpipla",
    "Rajula",
    "Ranavav",
    "Rapar",
    "Roha",
    "Sabar Kantha",
    "Sachin",
    "Salaya",
    "Sanand",
    "Sankheda",
    "Sarkhej",
    "Savarkundla",
    "Sayla",
    "Shahpur",
    "Shivrajpur",
    "Siddhapur",
    "Siddhpur",
    "Sihor",
    "Sikka",
    "Sinor",
    "Sojitra",
    "Songadh",
    "Surat",
    "Surendranagar",
    "Talaja",
    "Tankara",
    "Tapi",
    "Than",
    "Thangadh",
    "Tharad",
    "Thasra",
    "The Dangs",
    "Umrala",
    "Umreth",
    "Un",
    "Una",
    "Unjha",
    "Upleta",
    "Utran",
    "Vadnagar",
    "Vadodara",
    "Vaghodia",
    "Valabhipur",
    "Vallabh Vidyanagar",
    "Vallabhipur",
    "Valsad",
    "Vansada",
    "Vansda",
    "Vapi",
    "Vartej",
    "Vasa",
    "Vaso",
    "Vejalpur",
    "Veraval",
    "Vijapur",
    "Vinchhiya",
    "Vinchia",
    "Virpur",
    "Visavadar",
    "Visnagar",
    "Vyara",
    "Wadhai",
    "Wadhwan",
    "Waghai",
    "Wankaner",
];

export const AndhraPradesh = [
    "Addanki",
    "adoni",
    "Akasahebpet",
    "Akividu",
    "Akkarampalle",
    "Amalapuram",
    "Amudalavalasa",
    "Anakapalle",
    "Anantapur",
    "Atmakūr",
    "Attili",
    "Avanigadda",
    "Badvel",
    "Banganapalle",
    "Bapatla",
    "Betamcherla",
    "Bhattiprolu",
    "Bhimavaram",
    "Bhimunipatnam",
    "Bobbili",
    "Challapalle",
    "Chemmumiahpet",
    "Chilakalūrupet",
    "Chinnachowk",
    "Chipurupalle",
    "Chirala",
    "Chittoor",
    "Chodavaram",
    "Cuddapah",
    "Cumbum",
    "Darsi",
    "Dharmavaram",
    "Dhone",
    "Diguvametta",
    "East Godavari",
    "Elamanchili",
    "Ellore",
    "Emmiganūr",
    "Erraguntla",
    "Etikoppaka",
    "Gajuwaka",
    "Ganguvada",
    "Gannavaram",
    "Giddalūr",
    "Gokavaram",
    "Gorantla",
    "Govindapuram,Chilakaluripet,Guntur",
    "Gudivada",
    "Gudlavalleru",
    "Gūdūr",
    "Guntakal Junction",
    "Guntūr",
    "Hindupur",
    "Ichchapuram",
    "Jaggayyapeta",
    "Jammalamadugu",
    "Kadiri",
    "Kaikalūr",
    "Kakinada",
    "Kalyandurg",
    "Kamalapuram",
    "Kandukūr",
    "Kanigiri",
    "Kankipadu",
    "Kanuru",
    "Kavali",
    "Kolanukonda",
    "Kondapalle",
    "Korukollu",
    "Kosigi",
    "Kovūr",
    "Kovvūr",
    "Krishna",
    "Kuppam",
    "Kurnool",
    "Macherla",
    "Machilipatnam",
    "Madanapalle",
    "Madugula",
    "Mandapeta",
    "Mandasa",
    "Mangalagiri",
    "Markapur",
    "Nagari",
    "Nagireddipalli",
    "Nandigama",
    "Nandikotkūr",
    "Nandyal",
    "Narasannapeta",
    "Narasapur",
    "Narasaraopet",
    "Narasingapuram",
    "Narayanavanam",
    "Narsipatnam",
    "Nayudupet",
    "Nellore",
    "Nidadavole",
    "Nūzvid",
    "Ongole",
    "Pakala",
    "Palakollu",
    "Palasa",
    "Palkonda",
    "Pallevada",
    "Palmaner",
    "Parlakimidi",
    "Parvatipuram",
    "Pavuluru",
    "Pedana",
    "pedda nakkalapalem",
    "Peddapuram",
    "Penugonda",
    "Penukonda",
    "Phirangipuram",
    "Pippara",
    "Pithapuram",
    "Polavaram",
    "Ponnur",
    "Ponnūru",
    "Prakasam",
    "Proddatūr",
    "Pulivendla",
    "Punganūru",
    "Puttaparthi",
    "Puttūr",
    "Rajahmundry",
    "Ramachandrapuram",
    "Ramanayyapeta",
    "Ramapuram",
    "Rampachodavaram",
    "Rayachoti",
    "Rayadrug",
    "Razam",
    "Razampeta",
    "Razole",
    "Renigunta",
    "Repalle",
    "Salūr",
    "Samalkot",
    "Sattenapalle",
    "Singarayakonda",
    "Sompeta",
    "Srikakulam",
    "Sūlūru",
    "Tadepalle",
    "Tadepallegūdem",
    "Tadpatri",
    "Tanuku",
    "Tekkali",
    "Tirumala",
    "Tirupati",
    "Tuni",
    "Uravakonda",
    "vadlamuru",
    "Vadlapūdi",
    "Venkatagiri",
    "Vepagunta",
    "Vetapalem",
    "Vijayawada",
    "Vinukonda",
    "Visakhapatnam",
    "Vishakhapatnam",
    "Vizianagaram",
    "Vizianagaram District",
    "Vuyyūru",
    "West Godavari",
    "Yanam",
    "Yanamalakuduru",
    "Yarada",
];

export const Assam = [
    "Abhayapuri",
    "Amguri",
    "Badarpur",
    "Baksa",
    "Barpathar",
    "Barpeta",
    "Barpeta Road",
    "Basugaon",
    "Bihpuriagaon",
    "Bijni",
    "Bilasipara",
    "Bokajan",
    "Bokakhat",
    "Bongaigaon",
    "Cachar",
    "Chabua",
    "Chapar",
    "Chirang",
    "Darrang",
    "Dergaon",
    "Dhekiajuli",
    "Dhemaji",
    "Dhing",
    "Dhubri",
    "Dhuburi",
    "Dibrugarh",
    "Digboi",
    "Dima Hasao District",
    "Diphu",
    "Dispur",
    "Duliagaon",
    "Dum Duma",
    "Gauripur",
    "Goalpara",
    "Gohpur",
    "Golaghat",
    "Golakganj",
    "Goshaingaon",
    "Guwahati",
    "Haflong",
    "Hailakandi",
    "Hajo",
    "Hojai",
    "Howli",
    "Jogighopa",
    "Jorhat",
    "Kamrūp",
    "Kamrup Metropolitan",
    "Karbi anglong",
    "Karimganj",
    "Kharupatia",
    "Kokrajhar",
    "Lakhimpur",
    "Lakhipur",
    "Lala",
    "Lumding Railway Colony",
    "Mahur",
    "Maibong",
    "Makum",
    "Mangaldai",
    "Mariani",
    "Moranha",
    "Morigaon",
    "Nagaon",
    "Nahorkatiya",
    "Nalbari",
    "Namrup",
    "Nazira",
    "North Guwahati",
    "North Lakhimpur",
    "Numaligarh",
    "Palasbari",
    "Raha",
    "Rangapara",
    "Rangia",
    "Sapatgram",
    "Sarupathar",
    "Sibsagar",
    "Silapathar",
    "Silchar",
    "Soalkuchi",
    "Sonari",
    "Sonitpur",
    "Sorbhog",
    "Tezpur",
    "Tinsukia",
    "Titabar",
    "Udalguri"
]

export const Bihar = [
    "Amarpur",
    "Araria",
    "Arrah",
    "Arwal",
    "Asarganj",
    "Aurangabad",
    "Bagaha",
    "Bahadurganj",
    "Bairagnia",
    "Baisi",
    "Bakhtiyarpur",
    "Bangaon",
    "Banka",
    "Banmankhi",
    "Bar Bigha",
    "Barauli",
    "Barh",
    "Barhiya",
    "Bariarpur",
    "Baruni",
    "Begusarai",
    "Belsand",
    "Bettiah",
    "Bhabhua",
    "Bhagalpur",
    "Bhagirathpur",
    "Bhawanipur",
    "Bhojpur",
    "Bihar Sharif",
    "Bihariganj",
    "Bikramganj",
    "Birpur",
    "Buddh Gaya",
    "Buxar",
    "Chakia",
    "Chapra",
    "Chhatapur",
    "Colgong",
    "Dalsingh Sarai",
    "Darbhanga",
    "Daudnagar",
    "Dehri",
    "Dhaka",
    "Dighwara",
    "Dinapore",
    "Dumra",
    "Dumraon",
    "Fatwa",
    "Forbesganj",
    "Gaya",
    "Ghoga",
    "Gopalganj",
    "Hajipur",
    "Hilsa",
    "Hisua",
    "Islampur",
    "Jagdispur",
    "Jahanabad",
    "Jamalpur",
    "Jamui",
    "Jamūi",
    "Jaynagar",
    "Jehanabad",
    "Jha-Jha",
    "Jhanjharpur",
    "Jogbani",
    "Kaimur District",
    "Kasba",
    "Katihar",
    "Khagaria",
    "Khagaul",
    "Kharagpur",
    "Khusropur",
    "Kishanganj",
    "Koath",
    "Koelwar",
    "Lakhisarai",
    "Lalganj",
    "Luckeesarai",
    "Madhepura",
    "Madhipura",
    "Madhubani",
    "Maharajgani",
    "Mairwa",
    "Maner",
    "Manihari",
    "Marhaura",
    "Masaurhi Buzurg",
    "Mohiuddinnagar",
    "Mokameh",
    "Monghyr",
    "Mothihari",
    "Munger",
    "Murliganj",
    "Muzaffarpur",
    "Nabinagar",
    "Nalanda",
    "Nasriganj",
    "Naugachhia",
    "Nawada",
    "Nirmali",
    "Pashchim Champaran",
    "Patna",
    "Piro",
    "Pupri",
    "Pūrba Champaran",
    "Purnia",
    "Rafiganj",
    "Raghunathpur",
    "Rajgir",
    "Ramnagar",
    "Raxaul",
    "Revelganj",
    "Rohtas",
    "Rusera",
    "Sagauli",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Shahbazpur",
    "Shahpur",
    "Sheikhpura",
    "Sheohar",
    "Sherghati",
    "Silao",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Teghra",
    "Tekari",
    "Thakurganj",
    "Vaishali",
    "Waris Aliganj"
];

export const Goa = [
    "Aldona",
    "Arambol",
    "Baga",
    "Bambolim",
    "Bandora",
    "Benaulim",
    "Calangute",
    "Candolim",
    "Carapur",
    "Cavelossim",
    "Chicalim",
    "Chinchinim",
    "Colovale",
    "Colva",
    "Cortalim",
    "Cuncolim",
    "Curchorem",
    "Curti",
    "Davorlim",
    "Dicholi",
    "Goa Velha",
    "Guirim",
    "Jua",
    "Kankon",
    "Madgaon",
    "Mapuca",
    "Morjim",
    "Mormugao",
    "Navelim",
    "North Goa",
    "Palle",
    "Panaji",
    "Pernem",
    "Ponda",
    "Quepem",
    "Queula",
    "Raia",
    "Saligao",
    "Sancoale",
    "Sanguem",
    "Sanquelim",
    "Sanvordem",
    "Serula",
    "Solim",
    "South Goa",
    "Taleigao",
    "Vagator",
    "Valpoy",
    "Varca",
    "Vasco da Gama"
];

export const HimachalPradesh = [
    "Arki",
    "Baddi",
    "Banjar",
    "Bilaspur",
    "Chamba",
    "Chaupal",
    "Chowari",
    "Chuari Khas",
    "Dagshai",
    "Dalhousie",
    "Daulatpur",
    "Dera Gopipur",
    "Dharamsala",
    "Gagret",
    "Ghumarwin",
    "Hamirpur",
    "Jawala Mukhi",
    "Jogindarnagar",
    "Jubbal",
    "Jutogh",
    "Kalka",
    "Kangar",
    "Kangra",
    "Kasauli",
    "Kinnaur",
    "Kotkhai",
    "Kotla",
    "Kulu",
    "Kyelang",
    "Lahul and Spiti",
    "Manali",
    "Mandi",
    "Nadaun",
    "Nagar",
    "Nagrota",
    "Nahan",
    "Nalagarh",
    "Palampur",
    "Pandoh",
    "Paonta Sahib",
    "Parwanoo",
    "Rajgarh",
    "Rampur",
    "Rohru",
    "Sabathu",
    "Santokhgarh",
    "Sarahan",
    "Sarka Ghat",
    "Seoni",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Sundarnagar",
    "Theog",
    "Tira Sujanpur",
    "Una",
    "Yol"
];

export const Jharkhand = [
    "Bagra",
    "Barka Kana",
    "Barki Saria",
    "Barwadih",
    "Bhojudih",
    "Bokaro",
    "Būndu",
    "Chaibasa",
    "Chakradharpur",
    "Chakulia",
    "Chandil",
    "Chas",
    "Chatra",
    "Chiria",
    "Daltonganj",
    "Deogarh",
    "Dhanbad",
    "Dhanwar",
    "Dugda",
    "Dumka",
    "Garhwa",
    "Ghatsila",
    "Giridih",
    "Gobindpur",
    "Godda",
    "Gomoh",
    "Gopinathpur",
    "Gua",
    "Gumia",
    "Gumla",
    "Hazaribag",
    "Hazaribagh",
    "Hesla",
    "Husainabad",
    "Jagannathpur",
    "Jamadoba",
    "Jamshedpur",
    "Jamtara",
    "Jasidih",
    "Jharia",
    "Jugsalai",
    "Jumri Tilaiya",
    "Kalikapur",
    "Kandra",
    "Kanke",
    "Katras",
    "Kenduadih",
    "Kharsawan",
    "Khunti",
    "Kodarma",
    "Kuju",
    "Latehar",
    "Lohardaga",
    "Madhupur",
    "Malkera",
    "Manoharpur",
    "Mugma",
    "Mushabani",
    "Neturhat",
    "Nirsa",
    "Noamundi",
    "Pakur",
    "Palamu",
    "Pashchim Singhbhūm",
    "patamda",
    "Pathardih",
    "Purba Singhbhum",
    "Ramgarh",
    "Ranchi",
    "Ray",
    "Sahibganj",
    "Saraikela",
    "Sarubera",
    "Sijua",
    "Simdega",
    "Sini",
    "Topchanchi"
];

export const Karnataka = [
    "Afzalpur",
    "Ajjampur",
    "Aland",
    "Alnavar",
    "Alūr",
    "Anekal",
    "Ankola",
    "Annigeri",
    "Arkalgūd",
    "Arsikere",
    "Athni",
    "Aurad",
    "Badami",
    "Bagalkot",
    "Bagepalli",
    "Bail-Hongal",
    "Ballari",
    "Banavar",
    "Bangalore Rural",
    "Bangalore Urban",
    "Bangarapet",
    "Bannūr",
    "Bantval",
    "Basavakalyan",
    "Basavana Bagevadi",
    "Belgaum",
    "Bellary",
    "Bellūru",
    "Beltangadi",
    "Belūr",
    "Bengaluru",
    "Bhadravati",
    "Bhalki",
    "Bhatkal",
    "Bidar",
    "Bijapur",
    "Bijapur",
    "Bilgi",
    "Birūr",
    "Byadgi",
    "Byndoor",
    "Canacona",
    "Challakere",
    "Chamrajnagar",
    "Channagiri",
    "Channapatna",
    "Channarayapatna",
    "Chik Ballapur",
    "Chikkaballapur",
    "Chikmagalur",
    "Chikmagalūr",
    "Chiknayakanhalli",
    "Chikodi",
    "Chincholi",
    "Chintamani",
    "Chitapur",
    "Chitradurga",
    "Closepet",
    "Coondapoor",
    "Dakshina Kannada",
    "Dandeli",
    "Davanagere",
    "Davangere",
    "Devanhalli",
    "Dharwad",
    "Dod Ballapur",
    "French Rocks",
    "Gadag",
    "Gadag-Betageri",
    "Gajendragarh",
    "Gangawati",
    "Gangolli",
    "Gokak",
    "Gokarna",
    "Goribidnūr",
    "Gorūr",
    "Gubbi",
    "Gudibanda",
    "Gulbarga",
    "Guledagudda",
    "Gundlupēt",
    "Gurmatkal",
    "Hadagalli",
    "Haliyal",
    "Hampi",
    "Hangal",
    "Harihar",
    "Harpanahalli",
    "Hassan",
    "Haveri",
    "Haveri",
    "Heggadadevankote",
    "Hirekerūr",
    "Hiriyūr",
    "Holalkere",
    "Hole Narsipur",
    "Homnabad",
    "Honavar",
    "Honnali",
    "Hosakote",
    "Hosanagara",
    "Hosangadi",
    "Hosdurga",
    "Hoskote",
    "Hospet",
    "Hubli",
    "Hukeri",
    "Hungund",
    "Hunsūr",
    "Ilkal",
    "Indi",
    "Jagalūr",
    "Jamkhandi",
    "Jevargi",
    "Kadūr",
    "Kalghatgi",
    "Kampli",
    "Kankanhalli",
    "Karkala",
    "Karwar",
    "Kavalūr",
    "Kerūr",
    "Khanapur",
    "Kodagu",
    "Kodigenahalli",
    "Kodlipet",
    "Kolar",
    "Kolar",
    "Kollegal",
    "Konanūr",
    "Konnūr",
    "Koppa",
    "Koppal",
    "Koratagere",
    "Kottūru",
    "Krishnarajpet",
    "Kudachi",
    "Kūdligi",
    "Kumsi",
    "Kumta",
    "Kundgol",
    "Kunigal",
    "Kurgunta",
    "Kushalnagar",
    "Kushtagi",
    "Lakshmeshwar",
    "Lingsugūr",
    "Londa",
    "Maddagiri",
    "Maddūr",
    "Madikeri",
    "Magadi",
    "Mahalingpur",
    "Malavalli",
    "Malpe",
    "Malūr",
    "Mandya",
    "Mangalore",
    "Manipal",
    "Manvi",
    "Mayakonda",
    "Melukote",
    "Mūdbidri",
    "Muddebihal",
    "Mudgal",
    "Mudgere",
    "Mudhol",
    "Mulbagal",
    "Mulgund",
    "Mūlki",
    "Mundargi",
    "Mundgod",
    "Munirabad",
    "Murudeshwara",
    "Mysore",
    "Nagamangala",
    "Nanjangūd",
    "Narasimharajapura",
    "Naregal",
    "Nargund",
    "Navalgund",
    "Nelamangala",
    "Nyamti",
    "Pangala",
    "Pavugada",
    "Piriyapatna",
    "Ponnampet",
    "Puttūr",
    "Rabkavi",
    "Raichūr",
    "Raichur",
    "Ramanagara",
    "Ranibennur",
    "Raybag",
    "Robertsonpet",
    "Ron",
    "Sadalgi",
    "Sagar",
    "Sakleshpur",
    "Sandūr",
    "Sanivarsante",
    "Sankeshwar",
    "Sargūr",
    "Saundatti",
    "Savanūr",
    "Seram",
    "Shahabad",
    "Shahpur",
    "Shiggaon",
    "Shikarpur",
    "Shimoga",
    "Shirhatti",
    "Shorapur",
    "Shrirangapattana",
    "Siddapur",
    "Sidlaghatta",
    "Sindgi",
    "Sindhnūr",
    "Sira",
    "Sirsi",
    "Siruguppa",
    "Someshwar",
    "Somvarpet",
    "Sorab",
    "Sravana Belgola",
    "Sringeri",
    "Srinivaspur",
    "Sulya",
    "Suntikoppa",
    "Talikota",
    "Tarikere",
    "Tekkalakote",
    "Terdal",
    "Tiptūr",
    "Tirthahalli",
    "Tirumakūdal Narsipur",
    "Tumkur",
    "Tumkūr",
    "Turuvekere",
    "Udupi",
    "Ullal",
    "Uttar Kannada",
    "Vadigenhalli",
    "Virarajendrapet",
    "Wadi",
    "Yadgir",
    "Yadgir",
    "Yelahanka",
    "Yelandūr",
    "Yelbarga",
    "Yellapur"
];

export const Kerala = [
    "Adūr",
    "Alappuzha",
    "Aluva",
    "Alwaye",
    "Angamali",
    "Aroor",
    "Arukutti",
    "Attingal",
    "Avanoor",
    "Azhikkal",
    "Badagara",
    "Beypore",
    "Changanacheri",
    "Chēlakara",
    "Chengannūr",
    "Cherpulassery",
    "Cherthala",
    "Chetwayi",
    "Chittūr",
    "Cochin",
    "Dharmadam",
    "Edakkulam",
    "Elur",
    "Erattupetta",
    "Ernakulam",
    "Ferokh",
    "Guruvayūr",
    "Idukki",
    "Iringal",
    "Irinjalakuda",
    "Kadakkavoor",
    "Kalamassery",
    "Kalavoor",
    "Kalpatta",
    "Kannangad",
    "Kannavam",
    "Kannur",
    "Kasaragod",
    "Kasaragod District",
    "Kattanam",
    "Kayankulam",
    "Kizhake Chalakudi",
    "Kodungallūr",
    "Kollam",
    "Kotamangalam",
    "Kottayam",
    "Kovalam",
    "Kozhikode",
    "Kumbalam",
    "Kunnamangalam",
    "Kunnamkulam",
    "Kunnumma",
    "Kutiatodu",
    "Kuttampuzha",
    "Lalam",
    "Mahē",
    "Malappuram",
    "Manjeri",
    "Manjēshvar",
    "Mannarakkat",
    "Marayur",
    "Mattanur",
    "Mavelikara",
    "Mavoor",
    "Muluppilagadu",
    "Munnar",
    "Mūvattupula",
    "Muvattupuzha",
    "Nadapuram",
    "Naduvannūr",
    "Nedumangad",
    "Neyyattinkara",
    "Nilēshwar",
    "Ottappalam",
    "Palackattumala",
    "Palakkad district",
    "Palghat",
    "Panamaram",
    "Pappinisshēri",
    "Paravūr Tekkumbhagam",
    "Pariyapuram",
    "Pathanamthitta",
    "Pattanamtitta",
    "Payyannūr",
    "Perumbavoor",
    "Perumpavūr",
    "Perya",
    "Piravam",
    "Ponmana",
    "Ponnani",
    "Punalūr",
    "Ramamangalam",
    "Shertallai",
    "Shōranūr",
    "Talipparamba",
    "Tellicherry",
    "Thanniyam",
    "Thiruvananthapuram",
    "Thrissur",
    "Thrissur District",
    "Tirur",
    "Tiruvalla",
    "Vaikam",
    "Varkala",
    "Vayalar",
    "Vettūr",
    "Wayanad"
];

export const Chhattisgarh = [
    "Akaltara",
    "Ambagarh Chauki",
    "Ambikapur",
    "Arang",
    "Baikunthpur",
    "Balod",
    "Baloda",
    "Baloda Bazar",
    "Basna",
    "Bastar",
    "Bemetara",
    "Bhanpuri",
    "Bhatapara",
    "Bhatgaon",
    "Bhilai",
    "Bijapur",
    "Bilaspur",
    "Champa",
    "Chhuikhadan",
    "Deori",
    "Dhamtari",
    "Dongargaon",
    "Dongargarh",
    "Durg",
    "Gandai",
    "Gariaband",
    "Gaurela",
    "Gharghoda",
    "Gidam",
    "Jagdalpur",
    "Janjgir",
    "Janjgir-Champa",
    "Jashpur",
    "Jashpurnagar",
    "Jūnagarh",
    "Kabeerdham",
    "Kanker",
    "Katghora",
    "Kawardha",
    "Khairagarh",
    "Khamharia",
    "Kharod",
    "Kharsia",
    "Kirandul",
    "Kondagaon",
    "Korba",
    "Koriya",
    "Kota",
    "Kotaparh",
    "Kumhari",
    "Kurud",
    "Lormi",
    "Mahasamund",
    "Mungeli",
    "Narayanpur",
    "Narharpur",
    "Pandaria",
    "Pandatarai",
    "Pasan",
    "Patan",
    "Pathalgaon",
    "Pendra",
    "Pithora",
    "Raigarh",
    "Raipur",
    "Raj Nandgaon",
    "Raj-Nandgaon",
    "Ramanuj Ganj",
    "Ratanpur",
    "Sakti",
    "Saraipali",
    "Sarangarh",
    "Seorinarayan",
    "Simga",
    "Surguja",
    "Takhatpur",
    "Umarkot",
    "Uttar Bastar Kanker"
];

export const MadhyaPradesh = [
    "Ayodhya",
    "Agar",
    "Ajaigarh",
    "Akodia",
    "Alampur",
    "Alirajpur",
    "Alot",
    "Amanganj",
    "Amarkantak",
    "Amarpatan",
    "Amarwara",
    "Ambah",
    "Amla",
    "Anjad",
    "Antri",
    "Anuppur",
    "Anūppur",
    "aron",
    "Ashoknagar",
    "Ashta",
    "Babai",
    "Badarwas",
    "Badnawar",
    "Bag",
    "Bagli",
    "Baihar",
    "Baikunthpur",
    "Bakshwaho",
    "Balaghat",
    "Baldeogarh",
    "Bamna",
    "Bamor Kalan",
    "Bamora",
    "Banda",
    "Barela",
    "Barghat",
    "Bargi",
    "Barhi",
    "Barwani",
    "Basoda",
    "Begamganj",
    "Beohari",
    "Berasia",
    "Betma",
    "Betūl",
    "Betūl Bazar",
    "Bhabhra",
    "Bhainsdehi",
    "Bhander",
    "Bhanpura",
    "Bhawaniganj",
    "Bhikangaon",
    "Bhind",
    "Bhitarwar",
    "Bhopal",
    "Biaora",
    "Bijawar",
    "Bijrauni",
    "Bodri",
    "Burhanpur",
    "Burhar",
    "Chanderi",
    "Chandia",
    "Chandla",
    "Chhatarpur",
    "Chhindwara",
    "Chichli",
    "Chorhat",
    "Daboh",
    "Dabra",
    "Damoh",
    "Datia",
    "Deori Khas",
    "Depalpur",
    "Dewas",
    "Dhamnod",
    "Dhana",
    "Dhar",
    "Dharampuri",
    "Dindori",
    "Etawa",
    "Gadarwara",
    "Garha Brahman",
    "Garhakota",
    "Gautampura",
    "Ghansor",
    "Gogapur",
    "Gohadi",
    "Govindgarh",
    "Guna",
    "Gurh",
    "Gwalior",
    "Harda",
    "Harda Khas",
    "Harpalpur",
    "Harrai",
    "Harsūd",
    "Hatod",
    "Hatta",
    "Hindoria",
    "Hoshangabad",
    "Iawar",
    "Ichhawar",
    "Iklehra",
    "Indore",
    "Isagarh",
    "Itarsi",
    "Jabalpur",
    "Jaisinghnagar",
    "Jaithari",
    "Jamai",
    "Jaora",
    "Jatara",
    "Jawad",
    "Jhabua",
    "Jiran",
    "Jobat",
    "Jora",
    "Kailaras",
    "Kaimori",
    "Kannod",
    "Kareli",
    "Karera",
    "Karrapur",
    "Kasrawad",
    "Katangi",
    "Katni",
    "Khachrod",
    "Khailar",
    "Khajuraho Group of Monuments",
    "Khamaria",
    "Khandwa",
    "Khandwa district",
    "Khargapur",
    "Khargone",
    "Khategaon",
    "Khilchipur",
    "Khirkiyan",
    "Khujner",
    "Khurai",
    "Kolaras",
    "Korwai",
    "Kotar",
    "Kothi",
    "Kotma",
    "Kotwa",
    "Kukshi",
    "Kumbhraj",
    "Lahar",
    "Lakhnadon",
    "Leteri",
    "Lodhikheda",
    "Machalpur",
    "Madhogarh",
    "Maheshwar",
    "Mahgawan",
    "Maihar",
    "Majholi",
    "Maksi",
    "Malhargarh",
    "Manasa",
    "Manawar",
    "Mandideep",
    "Mandla",
    "Mandleshwar",
    "Mandsaur",
    "Mangawan",
    "Manpur",
    "Mau",
    "Mauganj",
    "Mihona",
    "Mohgaon",
    "Morar",
    "Morena",
    "Multai",
    "Mundi",
    "Mungaoli",
    "Murwara",
    "Nagda",
    "Nagod",
    "Naigarhi",
    "Nainpur",
    "Namli",
    "Naraini",
    "Narayangarh",
    "Narsimhapur",
    "Narsinghgarh",
    "Narwar",
    "Nasrullahganj",
    "Neemuch",
    "Nepanagar",
    "Orchha",
    "Pachmarhi",
    "Palera",
    "Pali",
    "Panagar",
    "Panara",
    "Pandhana",
    "Pandhurna",
    "Panna",
    "Pansemal",
    "Parasia",
    "Patan",
    "Patharia",
    "Pawai",
    "Petlawad",
    "Piploda",
    "Pithampur",
    "Porsa",
    "Punasa",
    "Raghogarh",
    "Rahatgarh",
    "Raisen",
    "Rajgarh",
    "Rajnagar",
    "Rajpur",
    "Rampura",
    "Ranapur",
    "Ratangarh",
    "Ratlam",
    "Rehli",
    "Rehti",
    "Rewa",
    "Sabalgarh",
    "Sagar",
    "Sailana",
    "Sanawad",
    "Sanchi",
    "Sanwer",
    "Sarangpur",
    "Satna",
    "Satwas",
    "Saugor",
    "Sausar",
    "Sehore",
    "Sendhwa",
    "Seondha",
    "Seoni",
    "Seoni Malwa",
    "Shahdol",
    "Shahgarh",
    "Shahpur",
    "Shahpura",
    "Shajapur",
    "Shamgarh",
    "Sheopur",
    "Shivpuri",
    "Shujalpur",
    "Sidhi",
    "Sihora",
    "Simaria",
    "Singoli",
    "Singrauli",
    "Sirmaur",
    "Sironj",
    "Sitamau",
    "Sohagi",
    "Sohagpur",
    "Sultanpur",
    "Susner",
    "Tal",
    "Talen",
    "Tarana",
    "Tekanpur",
    "Tendūkheda",
    "Teonthar",
    "Thandla",
    "Tikamgarh",
    "Tirodi",
    "Udaipura",
    "Ujjain",
    "Ukwa",
    "Umaria",
    "Umaria District",
    "Umri",
    "Unhel",
    "Vidisha",
    "Waraseoni"
];

export const Maharashtra = [
    "Achalpur",
    "Ahiri",
    "Ahmadnagar",
    "Ahmadpur",
    "Airoli",
    "Ajra",
    "Akalkot",
    "Akola",
    "Akot",
    "Alandi",
    "Alibag",
    "Allapalli",
    "Amalner",
    "Amarnath",
    "Ambad",
    "Ambajogai",
    "Amravati",
    "Amravati Division",
    "Anjangaon",
    "Anshing",
    "arangaon",
    "Artist Village",
    "arvi",
    "Ashta",
    "Ashti",
    "Aurangabad",
    "Ausa",
    "Badlapur",
    "Balapur",
    "Ballalpur",
    "Baramati",
    "Barsi",
    "Basmat",
    "Beed",
    "Bhandara",
    "Bhayandar",
    "Bhigvan",
    "Bhiwandi",
    "Bhor",
    "Bhudgaon",
    "Bhūm",
    "Bhusaval",
    "Bid",
    "Biloli",
    "Boisar",
    "Borivli",
    "Buldana",
    "Chakan",
    "Chalisgaon",
    "Chanda",
    "Chandor",
    "Chandrapur",
    "Chandur",
    "Chandūr",
    "Chandūr Bazar",
    "Chicholi",
    "Chikhli",
    "Chinchani",
    "Chiplūn",
    "Chopda",
    "Dabhol",
    "Dahanu",
    "Darwha",
    "Daryapur",
    "Dattapur",
    "Daulatabad",
    "Daund",
    "Dehu",
    "Deolali",
    "Deoli",
    "Deūlgaon Raja",
    "Dharangaon",
    "Dharmabad",
    "Dharūr",
    "Dhule",
    "Dhūlia",
    "Diglūr",
    "Digras",
    "Dombivli",
    "Dondaicha",
    "Dudhani",
    "Durgapur",
    "Erandol",
    "Faizpur",
    "Gadchiroli",
    "Gadhinglaj",
    "Gangakher",
    "Gangapur",
    "Gevrai",
    "Ghatanji",
    "Ghoti Budrukh",
    "Ghugus",
    "Gondia",
    "Gondiya",
    "Goregaon",
    "Guhagar",
    "Hadgaon",
    "Harnai",
    "Hinganghat",
    "Hingoli",
    "Hirapur Hamesha",
    "Ichalkaranji",
    "Igatpuri",
    "Indapur",
    "Jaisingpur",
    "Jalgaon",
    "Jalgaon Jamod",
    "Jalna",
    "Jawhar",
    "Jejūri",
    "Jintūr",
    "Junnar",
    "Kagal",
    "Kalamb",
    "Kalamnūri",
    "Kalas",
    "Kalmeshwar",
    "Kalundri",
    "Kalyan",
    "Kamthi",
    "Kandri",
    "Kankauli",
    "Kannad",
    "Karad",
    "Karanja",
    "Karjat",
    "Karmala",
    "Kati",
    "Katol",
    "Khadki",
    "Khamgaon",
    "Khapa",
    "Kharakvasla",
    "Khed",
    "Khetia",
    "Khopoli",
    "Khuldabad",
    "Kinwat",
    "Kodoli",
    "Kolhapur",
    "Kondalwadi",
    "Kopargaon",
    "Koradi",
    "Koregaon",
    "Koynanagar",
    "Kudal",
    "Kurandvad",
    "Kurduvadi",
    "Lanja",
    "Lasalgaon",
    "Latur",
    "Lohogaon",
    "Lonar",
    "Lonavla",
    "Mahabaleshwar",
    "Mahad",
    "Maindargi",
    "Majalgaon",
    "Makhjan",
    "Malegaon",
    "Malkapur",
    "Malvan",
    "Manchar",
    "Mangrūl Pir",
    "Manmad",
    "Manor",
    "Mansar",
    "Manwat",
    "Matheran",
    "Mehekar",
    "Mhasla",
    "Mhasvad",
    "Mohpa",
    "Moram",
    "Morsi",
    "Mowad",
    "Mudkhed",
    "Mukher",
    "Mūl",
    "Mumbai",
    "Mumbai Suburban",
    "Murbad",
    "Murgūd",
    "Murtajapur",
    "Murud",
    "Nagothana",
    "Nagpur",
    "Nagpur Division",
    "Naldurg",
    "Nanded",
    "Nandgaon",
    "Nandūra Buzurg",
    "Nandurbar",
    "Nashik",
    "Nashik Division",
    "Navi Mumbai",
    "Neral",
    "Nilanga",
    "Nipani",
    "Osmanabad",
    "Ozar",
    "Pachora",
    "Paithan",
    "Palghar",
    "Panchgani",
    "Pandharpur",
    "Panhala",
    "Panvel",
    "Parbhani",
    "Parli Vaijnath",
    "Parola",
    "Partūr",
    "Patan",
    "Pathardi",
    "Pathri",
    "Patūr",
    "Pawni",
    "Pen",
    "Phaltan",
    "Pimpri",
    "Pipri",
    "Powai",
    "Pulgaon",
    "Pune",
    "Pune Division",
    "Pūrna",
    "Pusad",
    "Rahimatpur",
    "Rahuri",
    "Raigarh",
    "Rajapur",
    "Rajgurunagar",
    "Rajur",
    "Rajūra",
    "Ramtek",
    "Ratnagiri",
    "Raver",
    "Revadanda",
    "Risod",
    "Roha",
    "Sangamner",
    "Sangli",
    "Sangola",
    "Saoner",
    "Sasvad",
    "Satana",
    "Satara",
    "Satara Division",
    "Savantvadi",
    "Savda",
    "Selu",
    "Shahada",
    "Shahapur",
    "Shegaon",
    "Shiraguppi",
    "Shirdi",
    "Shirgaon",
    "Shirpur",
    "Shirwal",
    "Shivaji Nagar",
    "Shrigonda",
    "Sillod",
    "Sindhudurg",
    "Sindi",
    "Sinnar",
    "Sirūr",
    "Solapur",
    "Sonegaon",
    "Soygaon",
    "Srivardhan",
    "Surgana",
    "Talegaon Dabhade",
    "Taloda",
    "Tarapur",
    "Tasgaon",
    "Telhara",
    "Thane",
    "Trimbak",
    "Tuljapur",
    "Tumsar",
    "Udgir",
    "Ulhasnagar",
    "Umarga",
    "Umarkhed",
    "Umred",
    "Uran",
    "Vada",
    "Vaijapur",
    "Varangaon",
    "Vasind",
    "Vengurla",
    "Virar",
    "Vite",
    "Wadgaon",
    "Wai",
    "Wani",
    "Wardha",
    "Warora",
    "Warud",
    "Washim",
    "Yaval",
    "Yavatmal",
    "Yeola"
];

export const Manipur = [
    "Other",
    "Bishnupur",
    "Churachandpur",
    "Mayang Imphal",
    "Moirang",
    "Imphal East",
    "Imphal West",
    "Jiribam",
    "Kamjong",
    "Kangpokpi",
    "Noney",
    "Pherzawl",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul",
    "Kakching",
    "Chandel",
    "Wangjing",
    "Yairipok",
];

export const Meghalaya = [
    "Other",
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "North Garo Hills",
    "Ri-Bhoi",
    "South Garo Hills",
    "South West Garo Hills",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Williamnagar",
    "Baghmara",
    "Resubelpara",
    "Nongstoin",
    "Amlarem",
    "Mawkyrwat",
];

export const Mizoram = [
    "Aizawl",
    "Champhai",
    "Darlawn",
    "Khawhai",
    "Kolasib",
    "Kolasib district",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "North Vanlaiphai",
    "Saiha",
    "Sairang",
    "Saitlaw",
    "Serchhip",
    "Thenzawl"
];

export const DadraAndNagarHaveliDamanDiu = [
    "amli",
    "Dadra",
    "Dadra & Nagar Haveli",
    "Silvassa",
];

export const AndamanNicobar = [
    "Other",
    "Bamboo Flat",
    "Nicobar",
    "North and Middle Andaman",
    "South Andaman",
    "Port Blair",
    "Diglipur",
    "Mayabunder",
    "Rangat",
    "Havelock Island",
    "Car Nicobar",
    "Campbell Bay",
    "Nancowry",
    "Little Andaman",
    "Great Nicobar",
];

export const ArunachalPradesh = [
    "Other",
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Kurung Kumey",
    "Kra Daadi",
    "Lower Subansiri",
    "Upper Subansiri",
    "West Siang",
    "East Siang",
    "Siang",
    "Upper Siang",
    "Lower Siang",
    "Lower Dibang Valley",
    "Dibang Valley",
    "Anjaw",
    "Lohit",
    "Changlang",
    "Tirap",
    "Longding",
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Roing",
    "Tezu",
    "Bomdila",
    "Ziro",
    "Aalo",
    "Seppa",
    "Along",
    "Namsai",
    "Khonsa",
    "Miao",
];

export const Haryana = [
    "Ambala",
    "asandh",
    "Ateli Mandi",
    "Bahadurgarh",
    "Bara Uchana",
    "Barwala",
    "Bawal",
    "Beri Khas",
    "Bhiwani",
    "Bilaspur",
    "Būriya",
    "Charkhi Dadri",
    "Chhachhrauli",
    "Dabwali",
    "Dharuhera",
    "Ellenabad",
    "Faridabad",
    "Faridabad District",
    "Farrukhnagar",
    "Fatehabad",
    "Fatehabad District",
    "Firozpur Jhirka",
    "Gharaunda",
    "Gohana",
    "Gorakhpur",
    "Gurgaon",
    "Hansi",
    "Hasanpur",
    "Hisar",
    "Hodal",
    "Inda Chhoi",
    "Indri",
    "Jagadhri",
    "Jakhal",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Kalanaur",
    "Kalanwali",
    "Kanina Khas",
    "Karnal",
    "Kharkhauda",
    "Kheri Sampla",
    "Kurukshetra",
    "Ladwa",
    "Loharu",
    "Maham",
    "Mahendragarh",
    "Mandholi Kalan",
    "Mustafabad",
    "Narayangarh",
    "Narnaul",
    "Narnaund",
    "Narwana",
    "Nilokheri",
    "Nūh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Pataudi",
    "Pehowa",
    "Pinjaur",
    "Pūnahana",
    "Pūndri",
    "Radaur",
    "Rania",
    "Ratia",
    "Rewari",
    "Rewari District",
    "Rohtak",
    "Safidon",
    "Samalkha",
    "Shadipur Julana",
    "Shahabad",
    "Sirsa",
    "Sohna",
    "Sonipat",
    "Taoru",
    "Thanesar",
    "Tohana",
    "Tosham",
    "Uklana",
    "Yamunanagar"
]

export const Puducherry = [
    "Other",
    "Puducherry",
    "Mahe",
    "Karaikal",
    "Yanam",
    "Ozhukarai",
    "Villianur",
    "Mudaliarpet",
    "Bahour",
    "Nellithope",
    "Lawspet",
];

export const Lakshadweep = [
    "Other",
    "Lakshadweep",
    "Kavaratti",
    "Agatti",
    "Amini",
    "Andrott",
    "Bangaram",
    "Bitra",
    "Chetlat",
    "Kadmat",
    "Kalpeni",
    "Kilthan",
    "Minicoy",
];

export const WestBengal = [
    "Ahmedpur",
    "Aistala",
    "Aknapur",
    "Alipur Duar",
    "Alipurduar",
    "amlagora",
    "Amta",
    "Amtala",
    "Andal",
    "Arambagh community development block",
    "Asansol",
    "Ashoknagar Kalyangarh",
    "Badkulla",
    "Baduria",
    "Bagdogra",
    "Bagnan",
    "Bagula",
    "Bahula",
    "Baidyabati",
    "Bakreswar",
    "Balarampur",
    "Bali Chak",
    "Bally",
    "Balurghat",
    "Bamangola community development block",
    "Baneswar",
    "Bangaon",
    "Bankra",
    "Bankura",
    "Bansberia",
    "Bansihari community development block",
    "Barabazar",
    "Baranagar",
    "Barasat",
    "Bardhaman",
    "Barjora",
    "Barrackpore",
    "Baruipur",
    "Basanti",
    "Basirhat",
    "Bawali",
    "Begampur",
    "Belda",
    "Beldanga",
    "Beliatore",
    "Berhampore",
    "Bhadreswar",
    "Bhandardaha",
    "Bhatpara",
    "Birbhum district",
    "Birpara",
    "Bishnupur",
    "Bolpur",
    "Budge Budge",
    "Canning",
    "Chakapara",
    "Chakdaha",
    "Champadanga",
    "Champahati",
    "Champdani",
    "Chandannagar",
    "Chandrakona",
    "Chittaranjan",
    "Churulia",
    "Contai",
    "Cooch Behar",
    "Cossimbazar",
    "Dakshin Dinajpur district",
    "Dalkola",
    "Dam Dam",
    "Darjeeling",
    "Daulatpur",
    "Debagram",
    "Debipur",
    "Dhaniakhali community development block",
    "Dhulagari",
    "Dhulian",
    "Dhupguri",
    "Diamond Harbour",
    "Digha",
    "Dinhata",
    "Domjur",
    "Dubrajpur",
    "Durgapur",
    "Egra",
    "Falakata",
    "Farakka",
    "Fort Gloster",
    "Gaighata community development block",
    "Gairkata",
    "Gangadharpur",
    "Gangarampur",
    "Garui",
    "Garulia",
    "Ghatal",
    "Giria",
    "Gobardanga",
    "Gobindapur",
    "Gopalpur",
    "Gopinathpur",
    "Gorubathan",
    "Gosaba",
    "Gosanimari",
    "Gurdaha",
    "Guskhara",
    "Habra",
    "Haldia",
    "Haldibari",
    "Halisahar",
    "Harindanga",
    "Haringhata",
    "Haripur",
    "Hasimara",
    "Hindusthan Cables Town",
    "Hooghly district",
    "Howrah",
    "Ichapur",
    "Indpur community development block",
    "Ingraj Bazar",
    "Islampur",
    "Jafarpur",
    "Jaigaon",
    "Jalpaiguri",
    "Jamuria",
    "Jangipur",
    "Jaynagar Majilpur",
    "Jejur",
    "Jhalida",
    "Jhargram",
    "Jhilimili",
    "Kakdwip",
    "Kalaikunda",
    "Kaliaganj",
    "Kalimpong",
    "Kalna",
    "Kalyani",
    "Kamarhati",
    "Kamarpukur",
    "Kanchrapara",
    "Kandi",
    "Karimpur",
    "Katwa",
    "Kenda",
    "Keshabpur",
    "Kharagpur",
    "Kharar",
    "Kharba",
    "Khardaha",
    "Khatra",
    "Kirnahar",
    "Kolkata",
    "Konnagar",
    "Krishnanagar",
    "Krishnapur",
    "Kshirpai",
    "Kulpi",
    "Kultali",
    "Kulti",
    "Kurseong",
    "Lalgarh",
    "Lalgola",
    "Loyabad",
    "Madanpur",
    "Madhyamgram",
    "Mahiari",
    "Mahishadal community development block",
    "Mainaguri",
    "Manikpara",
    "Masila",
    "Mathabhanga",
    "Matiali community development block",
    "Matigara community development block",
    "Medinipur",
    "Mejia community development block",
    "Memari",
    "Mirik",
    "Mohanpur community development block",
    "Monoharpur",
    "Muragacha",
    "Muri",
    "Murshidabad",
    "Nabadwip",
    "Nabagram",
    "Nadia district",
    "Nagarukhra",
    "Nagrakata",
    "Naihati",
    "Naksalbari",
    "Nalhati",
    "Nalpur",
    "Namkhana community development block",
    "Nandigram",
    "Nangi",
    "Nayagram community development block",
    "North 24 Parganas district",
    "Odlabari",
    "Paikpara",
    "Panagarh",
    "Panchla",
    "Panchmura",
    "Pandua",
    "Panihati",
    "Panskura",
    "Parbatipur",
    "Paschim Medinipur district",
    "Patiram",
    "Patrasaer",
    "Patuli",
    "Pujali",
    "Puncha community development block",
    "Purba Medinipur district",
    "Purulia",
    "Raghudebbati",
    "Raghunathpur",
    "Raiganj",
    "Rajmahal",
    "Rajnagar community development block",
    "Ramchandrapur",
    "Ramjibanpur",
    "Ramnagar",
    "Rampur Hat",
    "Ranaghat",
    "Raniganj",
    "Raypur",
    "Rishra",
    "Sahapur",
    "Sainthia",
    "Salanpur community development block",
    "Sankarpur",
    "Sankrail",
    "Santipur",
    "Santoshpur",
    "Santuri community development block",
    "Sarenga",
    "Serampore",
    "Serpur",
    "Shyamnagar, West Bengal",
    "Siliguri",
    "Singur",
    "Sodpur",
    "Solap",
    "Sonada",
    "Sonamukhi",
    "Sonarpur community development block",
    "South 24 Parganas district",
    "Srikhanda",
    "Srirampur",
    "Suri",
    "Swarupnagar community development block",
    "Takdah",
    "Taki",
    "Tamluk",
    "Tarakeswar",
    "Titagarh",
    "Tufanganj",
    "Tulin",
    "Uchalan",
    "Ula",
    "Uluberia",
    "Uttar Dinajpur district",
    "Uttarpara Kotrung"
];

export const UttarPrades = [
    "Achhnera",
    "Afzalgarh",
    "Agra",
    "agra",
    "Ahraura",
    "Ajodhya",
    "Akbarpur",
    "Aliganj",
    "Aligarh",
    "Allahabad",
    "Allahganj",
    "Amanpur",
    "Ambahta",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Anandnagar",
    "Antu",
    "Anūpshahr",
    "Aonla",
    "Atarra",
    "Atrauli",
    "Atraulia",
    "Auraiya",
    "Auras",
    "azamgarh",
    "Azamgarh",
    "Baberu",
    "Babina",
    "Babrala",
    "Babugarh",
    "Bachhraon",
    "Bachhrawan",
    "Baghpat",
    "Bah",
    "Baheri",
    "Bahjoi",
    "Bahraich",
    "Bahraigh",
    "Bahsūma",
    "Bahua",
    "Bajna",
    "Bakewar",
    "Baldev",
    "Ballia",
    "Balrampur",
    "Banat",
    "Banbasa",
    "Banda",
    "Bangarmau",
    "Bansdih",
    "Bansgaon",
    "Bansi",
    "Bara Banki",
    "Baragaon",
    "Baraut",
    "Bareilly",
    "Barkhera Kalan",
    "Barsana",
    "Basti",
    "Behat",
    "Bela",
    "Beniganj",
    "Beswan",
    "Bewar",
    "Bhadohi",
    "Bhagwantnagar",
    "Bharthana",
    "Bharwari",
    "Bhinga",
    "Bhongaon",
    "Bidhūna",
    "Bighapur Khurd",
    "Bijnor",
    "Bikapur",
    "Bilari",
    "Bilariaganj",
    "Bilaspur",
    "Bilgram",
    "Bilhaur",
    "Bilsanda",
    "Bilsi",
    "Bilthra",
    "Bindki",
    "Bisalpur",
    "Bisauli",
    "Bisenda Buzurg",
    "Bishunpur Urf Maharajganj",
    "Biswan",
    "Bithūr",
    "Budaun",
    "Budhana",
    "Bulandshahr",
    "Captainganj",
    "Chail",
    "Chakia",
    "Chandauli",
    "Chandauli District",
    "Chandpur",
    "Chanduasi",
    "Charkhari",
    "Charthawal",
    "Chhaprauli",
    "Chharra",
    "Chhata",
    "Chhibramau",
    "Chhutmalpur",
    "Chillupar",
    "Chirgaon",
    "Chitrakoot",
    "Chopan",
    "Chunar",
    "Colonelganj",
    "Dadri",
    "Dalmau",
    "Dankaur",
    "Dasna",
    "Dataganj",
    "Daurala",
    "Dayal Bagh",
    "Deoband",
    "Deoranian",
    "Deoria",
    "Dewa",
    "Dhampur",
    "Dhanaura",
    "Dhaurahra",
    "Dibai",
    "Dohrighat",
    "Dostpur",
    "Dūdhi",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farah",
    "Faridnagar",
    "Faridpur",
    "Farrukhabad",
    "Fatehabad",
    "Fatehganj West",
    "Fatehgarh",
    "Fatehpur",
    "Fatehpur Chaurasi",
    "Fatehpur Sikri",
    "Firozabad",
    "Fyzabad",
    "Gajraula",
    "Gangoh",
    "Ganj Dundwara",
    "Ganj Muradabad",
    "Garautha",
    "Garhi Pūkhta",
    "Garhmuktesar",
    "Gautam Buddha Nagar",
    "Gawan",
    "Ghatampur",
    "Ghaziabad",
    "Ghazipur",
    "Ghiror",
    "Ghorawal",
    "Ghosi",
    "Gohand",
    "Gokul",
    "Gola Bazar",
    "Gola Gokarannath",
    "Gonda",
    "Gonda City",
    "Gopamau",
    "Gorakhpur",
    "Goshainganj",
    "Govardhan",
    "Greater Noida",
    "Gulaothi",
    "Gunnaur",
    "Gursahaiganj",
    "Gursarai",
    "Gyanpur",
    "Haldaur",
    "Hamirpur",
    "Handia",
    "Hapur",
    "Haraiya",
    "Hardoi",
    "Harduaganj",
    "Hasanpur",
    "Hastinapur",
    "Hata",
    "Hathras",
    "Iglas",
    "Ikauna",
    "Indergarh",
    "Islamnagar",
    "Itaunja",
    "Itimadpur",
    "Jagdishpur",
    "Jagnair",
    "Jahanabad",
    "Jahangirabad",
    "Jahangirpur",
    "Jainpur",
    "Jais",
    "Jalalabad",
    "Jalali",
    "Jalalpur",
    "Jalaun",
    "Jalesar",
    "Jansath",
    "Jarwal",
    "Jasrana",
    "Jaswantnagar",
    "Jaunpur",
    "Jewar",
    "Jhalu",
    "Jhansi",
    "Jhinjhak",
    "Jhinjhana",
    "Jhūsi",
    "Jyotiba Phule Nagar",
    "Kabrai",
    "Kachhwa",
    "Kadaura",
    "Kadipur",
    "Kaimganj",
    "Kairana",
    "Kakori",
    "Kakrala",
    "Kalinagar",
    "Kalpi",
    "Kamalganj",
    "Kampil",
    "Kandhla",
    "Kannauj",
    "Kanpur",
    "Kanpur Dehat",
    "Kant",
    "Kanth",
    "Karari",
    "Karhal",
    "Kasganj",
    "Katra",
    "Kaushambi District",
    "Kemri",
    "Khada",
    "Khaga",
    "Khair",
    "Khairabad",
    "Khalilabad",
    "Khanpur",
    "Kharela",
    "Khargupur",
    "Kharkhauda",
    "Khatauli",
    "Khekra",
    "Kheri",
    "Khudaganj",
    "Khurja",
    "Khūtar",
    "Kirakat",
    "Kiraoli",
    "Kiratpur",
    "Kishanpur",
    "Kishni",
    "Kithor",
    "Konch",
    "Kopaganj",
    "Kosi",
    "Kota",
    "Kotra",
    "Kulpahar",
    "Kunda",
    "Kundarkhi",
    "Kurara",
    "Kushinagar",
    "Laharpur",
    "Lakhimpur",
    "Lakhna",
    "Lalganj",
    "Lalitpur",
    "Lar",
    "Lawar Khas",
    "Loni",
    "Lucknow",
    "Lucknow District",
    "Machhlishahr",
    "Madhoganj",
    "Madhogarh",
    "Maghar",
    "Mahaban",
    "Maharaganj",
    "Maharajganj",
    "Mahmudabad",
    "Mahoba",
    "Maholi",
    "Mahroni",
    "Mailani",
    "Mainpuri",
    "Malihabad",
    "Mandawar",
    "Maniar",
    "Manikpur",
    "Manjhanpur",
    "Mankapur",
    "Marahra",
    "Mariahu",
    "Mataundh",
    "Mathura",
    "Mau",
    "Mau Aimma",
    "Maudaha",
    "Mauranwan",
    "Mawana",
    "Meerut",
    "Mehnagar",
    "Mehndawal",
    "Milak",
    "Miranpur",
    "Miranpur Katra",
    "Mirganj",
    "Mirzapur",
    "Misrikh",
    "Mohan",
    "Mohanpur",
    "Moradabad",
    "Moth",
    "Mubarakpur",
    "Mughal Sarai",
    "Muhammadabad",
    "Muradnagar",
    "Mursan",
    "Musafir-Khana",
    "Muzaffarnagar",
    "Nadigaon",
    "Nagina",
    "Nagram",
    "Najibabad",
    "Nakūr",
    "Nanauta",
    "Nandgaon",
    "Nanpara",
    "Narauli",
    "Naraura",
    "Nautanwa",
    "Nawabganj",
    "Nichlaul",
    "Nihtaur",
    "Niwari",
    "Nizamabad",
    "Noida",
    "Nūrpur",
    "Obra",
    "Orai",
    "Oran",
    "Pachperwa",
    "Padrauna",
    "Pahasu",
    "Pali",
    "Palia Kalan",
    "Parichha",
    "Parichhatgarh",
    "Parshadepur",
    "Patiali",
    "Patti",
    "Pawayan",
    "Phalauda",
    "Phaphūnd",
    "Phariha",
    "Phulpur",
    "Phūlpur",
    "Pihani",
    "Pilibhit",
    "Pilkhua",
    "Pinahat",
    "Pipraich",
    "Pratapgarh",
    "Pukhrayan",
    "Pūranpur",
    "Purwa",
    "Rabūpura",
    "Radhakund",
    "Rae Bareli",
    "Raebareli",
    "Rajapur",
    "Ramkola",
    "Ramnagar",
    "Rampur",
    "Rampura",
    "Ranipur",
    "Rasra",
    "Rasūlabad",
    "Rath",
    "Raya",
    "Renukūt",
    "Reoti",
    "Richha",
    "Robertsganj",
    "Rūdarpur",
    "Rura",
    "Sadabad",
    "Sadat",
    "Safipur",
    "Saharanpur",
    "Sahaspur",
    "Sahaswan",
    "Sahawar",
    "Saidpur",
    "Sakit",
    "Salon",
    "Sambhal",
    "Samthar",
    "Sandi",
    "Sandila",
    "Sant Kabir Nagar",
    "Sant Ravi Das Nagar",
    "Sarai akil",
    "Sarai Ekdil",
    "Sarai Mir",
    "Sarauli",
    "Sardhana",
    "Sarila",
    "Sasni",
    "Satrikh",
    "Saurikh",
    "Sector",
    "Seohara",
    "Shahabad",
    "Shahganj",
    "Shahi",
    "Shahjahanpur",
    "Shahjanpur",
    "Shahpur",
    "Shamli",
    "Shamsabad",
    "Shankargarh",
    "Shergarh",
    "Sherkot",
    "Shikarpūr",
    "Shikohabad",
    "Shishgarh",
    "Shrawasti",
    "Siddharthnagar",
    "Sidhauli",
    "Sidhpura",
    "Sikandarabad",
    "Sikandarpur",
    "Sikandra",
    "Sikandra Rao",
    "Sirathu",
    "Sirsa",
    "Sirsaganj",
    "Sirsi",
    "Sisauli",
    "Siswa Bazar",
    "Sitapur",
    "Sonbhadra",
    "Soron",
    "Suar",
    "Sultanpur",
    "Surianwan",
    "Tajpur",
    "Talbahat",
    "Talgram",
    "Tanda",
    "Thakurdwara",
    "Thana Bhawan",
    "Tikaitnagar",
    "Tikri",
    "Tilhar",
    "Tindwari",
    "Titron",
    "Tori-Fatehpur",
    "Tulsipur",
    "Tūndla",
    "Ugu",
    "Ujhani",
    "Ūn",
    "Unnao",
    "Usehat",
    "Utraula",
    "Varanasi",
    "Vrindavan",
    "Wazirganj",
    "Zafarabad",
    "Zaidpur",
    "Zamania"
];

export const Uttarakhand = [
    "Almora",
    "Bageshwar",
    "Barkot",
    "Bazpur",
    "Bhim Tal",
    "Bhowali",
    "Birbhaddar",
    "Chakrata",
    "Chamoli",
    "Champawat",
    "Clement Town",
    "Dehra Dūn",
    "Dehradun",
    "Devaprayag",
    "Dharchula",
    "Doiwala",
    "Dugadda",
    "Dwarahat",
    "Garhwal",
    "Haldwani",
    "Harbatpur",
    "Haridwar",
    "Jaspur",
    "Joshimath",
    "Kaladhūngi",
    "Kalagarh Project Colony",
    "Kashipur",
    "Khatima",
    "Kichha",
    "Kotdwara",
    "Laksar",
    "Lansdowne",
    "Lohaghat",
    "Manglaur",
    "Mussoorie",
    "Naini Tal",
    "Narendranagar",
    "Pauri",
    "Pipalkoti",
    "Pithoragarh",
    "Raipur",
    "Raiwala Bara",
    "Ramnagar",
    "Ranikhet",
    "Rishikesh",
    "Roorkee",
    "Rudraprayag",
    "Sitarganj",
    "Srinagar",
    "Sultanpur",
    "Tanakpur",
    "Tehri",
    "Tehri-Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
    "Vikasnagar"
];

export const Tripura = [
    "Agartala",
    "Amarpur",
    "ambasa",
    "Barjala",
    "Belonia",
    "Dhalai",
    "Dharmanagar",
    "Gomati",
    "Kailashahar",
    "Kamalpur",
    "Khowai",
    "North Tripura",
    "Ranir Bazar",
    "Sabrūm",
    "Sonamura",
    "South Tripura",
    "Udaipur",
    "Unakoti",
    "West Tripura"
];

export const Telangana = [
    "adilabad",
    "alampur",
    "Andol",
    "Asifabad",
    "Balapur",
    "Banswada",
    "Bellampalli",
    "Bhadrachalam",
    "Bhadradri Kothagudem",
    "Bhaisa",
    "Bhongir",
    "Bodhan",
    "Chandūr",
    "Chatakonda",
    "Dasnapur",
    "Devarkonda",
    "Dornakal",
    "Farrukhnagar",
    "Gaddi Annaram",
    "Gadwal",
    "Ghatkesar",
    "Gopalur",
    "Gūdūr",
    "Hyderabad",
    "Jagitial",
    "Jagtial",
    "Jangaon",
    "Jangoan",
    "Jayashankar Bhupalapally",
    "Jogulamba Gadwal",
    "Kagaznagar",
    "Kamareddi",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Kodar",
    "Koratla",
    "Kothapet",
    "Kottagūdem",
    "Kottapalli",
    "Kūkatpalli",
    "Kyathampalle",
    "Lakshettipet",
    "Lal Bahadur Nagar",
    "Mahabubabad",
    "Mahbūbabad",
    "Mahbūbnagar",
    "Malkajgiri",
    "Mancheral",
    "Mandamarri",
    "Manthani",
    "Manuguru",
    "Medak",
    "Medchal",
    "Medchal Malkajgiri",
    "Mirialgūda",
    "Nagar Karnūl",
    "Nalgonda",
    "Narayanpet",
    "Narsingi",
    "Naspur",
    "Nirmal",
    "Nizamabad",
    "Paloncha",
    "Palwancha",
    "Patancheru",
    "Peddapalli",
    "Quthbullapur",
    "Rajanna Sircilla",
    "Ramagundam",
    "Ramgundam",
    "Rangareddi",
    "Sadaseopet",
    "Sangareddi",
    "Sathupalli",
    "Secunderabad",
    "Serilingampalle",
    "Siddipet",
    "Singapur",
    "Sirpur",
    "Sirsilla",
    "Sriramnagar",
    "Suriapet",
    "Tandūr",
    "Uppal Kalan",
    "Vemalwada",
    "Vikarabad",
    "Wanparti",
    "Warangal",
    "Yellandu",
    "Zahirabad"
];

export const TamilNadu = [
    "Abiramam",
    "Adirampattinam",
    "Aduthurai",
    "Alagapuram",
    "Alandur",
    "Alanganallūr",
    "Alangayam",
    "alangudi",
    "alangulam",
    "alappakkam",
    "Alwa Tirunagari",
    "Ambasamudram",
    "Ambattūr",
    "Ambur",
    "Ammapettai",
    "Anamalais",
    "andippatti",
    "Annamalainagar",
    "Annavasal",
    "Annur",
    "Anthiyur",
    "Arakkonam",
    "Arantangi",
    "Arcot",
    "Arimalam",
    "Ariyalur",
    "Ariyalūr",
    "Arni",
    "Arumbavūr",
    "Arumuganeri",
    "Aruppukkottai",
    "Aruvankad",
    "attayyampatti",
    "Attur",
    "Auroville",
    "avadi",
    "Avinashi",
    "Ayakudi",
    "Ayyampettai",
    "Belūr",
    "Bhavani",
    "Bodinayakkanūr",
    "Chengam",
    "Chennai",
    "Chennimalai",
    "Chetput",
    "Chettipalaiyam",
    "Cheyyar",
    "Cheyyur",
    "Chidambaram",
    "Chingleput",
    "Chinna Salem",
    "Chinnamanūr",
    "Chinnasekkadu",
    "Cholapuram",
    "Coimbatore",
    "Colachel",
    "Cuddalore",
    "Cumbum",
    "Denkanikota",
    "Desūr",
    "Devadanappatti",
    "Devakottai",
    "Dhali",
    "Dharapuram",
    "Dharmapuri",
    "Dindigul",
    "Dūsi",
    "Elayirampannai",
    "Elumalai",
    "Eral",
    "Eraniel",
    "Erode",
    "Erumaippatti",
    "Ettaiyapuram",
    "Gandhi Nagar",
    "Gangaikondan",
    "Gangavalli",
    "Gingee",
    "Gobichettipalayam",
    "Gudalur",
    "Gudiyatham",
    "Gūduvancheri",
    "Gummidipundi",
    "Harūr",
    "Hosūr",
    "Idappadi",
    "Ilampillai",
    "Iluppūr",
    "Injambakkam",
    "Irugūr",
    "Jalakandapuram",
    "Jalarpet",
    "Jayamkondacholapuram",
    "Kadambūr",
    "Kadayanallur",
    "Kalakkadu",
    "Kalavai",
    "Kallakkurichchi",
    "Kallidaikurichi",
    "Kallupatti",
    "Kalugumalai",
    "Kamuthi",
    "Kanadukattan",
    "Kancheepuram",
    "Kanchipuram",
    "Kangayam",
    "Kanniyakumari",
    "Karaikkudi",
    "Karamadai",
    "Karambakkudi",
    "Kariapatti",
    "Karumbakkam",
    "Karur",
    "Katpadi",
    "Kattivakkam",
    "Kattupputtūr",
    "Kaveripatnam",
    "Kayalpattinam",
    "Kayattar",
    "Keelakarai",
    "Kelamangalam",
    "Kil Bhuvanagiri",
    "Kilvelur",
    "Kiranūr",
    "Kodaikanal",
    "Kodumudi",
    "Kombai",
    "Konganapuram",
    "Koothanallur",
    "Koradachcheri",
    "Korampallam",
    "Kotagiri",
    "Kottaiyūr",
    "Kovilpatti",
    "Krishnagiri",
    "Kulattūr",
    "Kulittalai",
    "Kumaralingam",
    "Kumbakonam",
    "Kunnattūr",
    "Kurinjippadi",
    "Kuttalam",
    "Kuzhithurai",
    "Lalgudi",
    "Madambakkam",
    "Madipakkam",
    "Madukkarai",
    "Madukkūr",
    "Madurai",
    "Madurantakam",
    "Mallapuram",
    "Mallasamudram",
    "Mallūr",
    "Manali",
    "Manalūrpettai",
    "Manamadurai",
    "Manappakkam",
    "Manapparai",
    "Manavalakurichi",
    "Mandapam",
    "Mangalam",
    "Mannargudi",
    "Marakkanam",
    "Marandahalli",
    "Masinigudi",
    "Mattūr",
    "Mayiladuthurai",
    "Melur",
    "Mettupalayam",
    "Mettuppalaiyam",
    "Mettur",
    "Minjūr",
    "Mohanūr",
    "Mudukulattūr",
    "Mūlanūr",
    "Musiri",
    "Muttupet",
    "Naduvattam",
    "Nagapattinam",
    "Nagercoil",
    "Namagiripettai",
    "Namakkal",
    "Nambiyūr",
    "Nambutalai",
    "Nandambakkam",
    "Nangavalli",
    "Nangilickondan",
    "Nanguneri",
    "Nannilam",
    "Naravarikuppam",
    "Nattam",
    "Nattarasankottai",
    "Needamangalam",
    "Neelankarai",
    "Negapatam",
    "Nellikkuppam",
    "Nilakottai",
    "Nilgiris",
    "Odugattūr",
    "Omalur",
    "Ooty",
    "Padmanabhapuram",
    "Palakkodu",
    "Palamedu",
    "Palani",
    "Palavakkam",
    "Palladam",
    "Pallappatti",
    "Pallattūr",
    "Pallavaram",
    "Pallikondai",
    "Pallipattu",
    "Pallippatti",
    "Panruti",
    "Papanasam",
    "Papireddippatti",
    "Papparappatti",
    "Paramagudi",
    "Pattukkottai",
    "Pennadam",
    "Pennagaram",
    "Pennathur",
    "Peraiyur",
    "Perambalur",
    "Peranamallūr",
    "Peranampattu",
    "Peravurani",
    "Periyakulam",
    "Periyanayakkanpalaiyam",
    "Periyanegamam",
    "Periyapatti",
    "Periyapattinam",
    "Perundurai",
    "Perungudi",
    "Perūr",
    "Pollachi",
    "Polūr",
    "Ponnamaravati",
    "Ponneri",
    "Poonamalle",
    "Porur",
    "Pudukkottai",
    "Puduppatti",
    "Pudūr",
    "Puduvayal",
    "Puliyangudi",
    "Puliyūr",
    "Pullambadi",
    "Punjai Puliyampatti",
    "Rajapalaiyam",
    "Ramanathapuram",
    "Rameswaram",
    "Rasipuram",
    "Saint Thomas Mount",
    "Salem",
    "Sathankulam",
    "Sathyamangalam",
    "Sattur",
    "Sayalkudi",
    "Seven Pagodas",
    "Sholinghur",
    "Singanallūr",
    "Singapperumalkovil",
    "Sirkazhi",
    "Sirumugai",
    "Sivaganga",
    "Sivagiri",
    "Sivakasi",
    "Srimushnam",
    "Sriperumbūdūr",
    "Srivaikuntam",
    "Srivilliputhur",
    "Suchindram",
    "Sulur",
    "Sūrandai",
    "Swamimalai",
    "Tambaram",
    "Tanjore",
    "Taramangalam",
    "Tattayyangarpettai",
    "Teni",
    "Thanjavur",
    "Tharangambadi",
    "Theni",
    "Thenkasi",
    "Thirukattupalli",
    "Thiruthani",
    "Thiruvaiyaru",
    "Thiruvallur",
    "Thiruvarur",
    "Thiruvidaimaruthur",
    "Thoothukkudi",
    "Thoothukudi",
    "Tindivanam",
    "Tinnanūr",
    "Tiruchchendur",
    "Tiruchengode",
    "Tiruchirappalli",
    "Tirukkoyilur",
    "Tirumullaivasal",
    "Tirunelveli",
    "Tirunelveli Kattabo",
    "Tiruppalaikudi",
    "Tirupparangunram",
    "Tiruppur",
    "Tiruppuvanam",
    "Tiruttangal",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvottiyūr",
    "Tisaiyanvilai",
    "Tondi",
    "Turaiyūr",
    "Udangudi",
    "Udumalaippettai",
    "Uppiliyapuram",
    "Usilampatti",
    "Uttamapalaiyam",
    "Uttiramerūr",
    "Ūttukkuli",
    "V.S.K.Valasai (Dindigul-Dist.)",
    "Vadakku Valliyūr",
    "Vadakku Viravanallur",
    "Vadamadurai",
    "Vadippatti",
    "Valangaiman",
    "Valavanur",
    "Vallam",
    "Valparai",
    "Vandalūr",
    "Vandavasi",
    "Vaniyambadi",
    "Vasudevanallūr",
    "Vattalkundu",
    "Vedaraniyam",
    "Vedasandūr",
    "Velankanni",
    "Vellanūr",
    "Vellore",
    "Velur",
    "Vengavasal",
    "Vettaikkaranpudur",
    "Vettavalam",
    "Vijayapuri",
    "Vikravandi",
    "Vilattikulam",
    "Villupuram",
    "Viraganūr",
    "Virudhunagar",
    "Virudunagar",
    "Vriddhachalam",
    "Walajapet",
    "Wallajahbad",
    "Wellington"
];

export const Sikkim = [
    "East District",
    "Gangtok",
    "Gyalshing",
    "Jorethang",
    "Mangan",
    "Namchi",
    "Naya Bazar",
    "North District",
    "Rangpo",
    "Singtam",
    "South District",
    "West District"
];

export const Ladakh = [
    "Other",
    "Kargil",
    "Leh",
    "Drass",
    "Nubra Valley",
    "Zanskar",
    "Hemis",
    "Diskit",
    "Padum",
];

export const JammuKashmir = [
    "Akhnūr",
    "Anantnag",
    "Awantipur",
    "Badgam",
    "Bandipore",
    "Bandipura",
    "Banihal",
    "Baramūla",
    "Batoti",
    "Bhadarwah",
    "Bijbehara",
    "Bishnah",
    "Doda",
    "Gandarbal",
    "Ganderbal",
    "Gho Brahmanan de",
    "Hajan",
    "Hiranagar",
    "Jammu",
    "Jaurian",
    "Kathua",
    "Katra",
    "Khaur",
    "Kishtwar",
    "Kūd",
    "Kulgam",
    "Kupwara",
    "Ladakh",
    "Magam",
    "Nawanshahr",
    "Noria",
    "Padam",
    "Pahlgam",
    "Parol",
    "Pattan",
    "Pulwama",
    "Punch",
    "Pūnch",
    "Qazigund",
    "Rajaori",
    "Rajauri",
    "Ramban",
    "Ramgarh",
    "Ramnagar",
    "Riasi",
    "Samba",
    "Shupiyan",
    "Sopur",
    "Soyibug",
    "Srinagar",
    "Sumbal",
    "Thang",
    "Thanna Mandi",
    "Tral",
    "Tsrar Sharif",
    "Udhampur",
    "Uri"
]

export const Delhi = [
    "Other",
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
    "Connaught Place",
    "Karol Bagh",
    "Chanakyapuri",
    "Paharganj",
    "Mayur Vihar",
    "Vasant Kunj",
    "Lajpat Nagar",
    "Dwarka",
    "Saket",
    "Rohini",
];

export const Rajasthan = [
    "Abhaneri",
    "abu",
    "abu Road",
    "Ajmer",
    "Aklera",
    "Alwar",
    "Amet",
    "Anta",
    "Anūpgarh",
    "asind",
    "Bagar",
    "Bakani",
    "Bali",
    "Balotra",
    "Bandikūi",
    "Banswara",
    "Baran",
    "Bari",
    "Bari Sadri",
    "Barmer",
    "Basi",
    "Basni",
    "Baswa",
    "Bayana",
    "Beawar",
    "Begūn",
    "Behror",
    "Bhadasar",
    "Bhadra",
    "Bharatpur",
    "Bhasawar",
    "Bhilwara",
    "Bhindar",
    "Bhinmal",
    "Bhiwadi",
    "Bhuma",
    "Bikaner",
    "Bilara",
    "Bissau",
    "Borkhera",
    "Būndi",
    "Chaksu",
    "Chechat",
    "Chhabra",
    "Chhapar",
    "Chhoti Sadri",
    "Chidawa",
    "Chittaurgarh",
    "Chūru",
    "Dariba",
    "Dausa",
    "Deoli",
    "Deshnoke",
    "Devgarh",
    "Dhaulpur",
    "Didwana",
    "Dig",
    "Dūngarpur",
    "Fatehpur",
    "Galiakot",
    "Ganganagar",
    "Gangapur",
    "Govindgarh",
    "Gulabpura",
    "Hanumangarh",
    "Hindaun",
    "Jahazpur",
    "Jaipur",
    "Jaisalmer",
    "Jaitaran",
    "Jalor",
    "Jalore",
    "Jhalawar",
    "Jhalrapatan",
    "Jhunjhunūn",
    "Jobner",
    "Jodhpur",
    "Kaman",
    "Kanor",
    "Kapren",
    "Karanpur",
    "Karauli",
    "Kekri",
    "Keshorai Patan",
    "Khandela",
    "Khanpur",
    "Khetri",
    "Kishangarh",
    "Kota",
    "Kotputli",
    "Kuchaman",
    "Kuchera",
    "Kūmher",
    "Kushalgarh",
    "Lachhmangarh Sikar",
    "Ladnūn",
    "Lakheri",
    "Lalsot",
    "Losal",
    "Mahwah",
    "Makrana",
    "Malpura",
    "Mandal",
    "Mandalgarh",
    "Mandawar",
    "Mangrol",
    "Manohar Thana",
    "Manoharpur",
    "Meethari Marwar",
    "Merta",
    "Mūndwa",
    "Nadbai",
    "Nagar",
    "Nagaur",
    "Nainwa",
    "Napasar",
    "Naraina",
    "Nasirabad",
    "Nathdwara",
    "Nawa",
    "Nawalgarh",
    "Neem ka Thana",
    "Nimaj",
    "Nimbahera",
    "Niwai",
    "Nohar",
    "Nokha",
    "Padampur",
    "Pali",
    "Partapur",
    "Parvatsar",
    "Phalodi",
    "Phulera",
    "Pilani",
    "Pilibangan",
    "Pindwara",
    "Pipar",
    "Pirawa",
    "Pokaran",
    "Pratapgarh",
    "Pushkar",
    "Raipur",
    "Raisinghnagar",
    "Rajakhera",
    "Rajaldesar",
    "Rajgarh",
    "Rajsamand",
    "Ramganj Mandi",
    "Ramgarh",
    "Rani",
    "Ratangarh",
    "Rawatbhata",
    "Rawatsar",
    "Ringas",
    "Sadri",
    "Salūmbar",
    "Sambhar",
    "Samdari",
    "Sanchor",
    "Sangaria",
    "Sangod",
    "Sardarshahr",
    "Sarwar",
    "Sawai Madhopur",
    "Shahpura",
    "Sheoganj",
    "Sikar",
    "Sirohi",
    "Siwana",
    "Sojat",
    "Sri Dūngargarh",
    "Sri Madhopur",
    "Sūjangarh",
    "Suket",
    "Sunel",
    "Sūrajgarh",
    "Sūratgarh",
    "Takhatgarh",
    "Taranagar",
    "Tijara",
    "Todabhim",
    "Todaraisingh",
    "Tonk",
    "Udaipur",
    "Udpura",
    "Uniara",
    "Wer"
]

export const Punjab = [
    "Abohar",
    "Adampur",
    "Ajitgarh",
    "Ajnala",
    "Akalgarh",
    "Alawalpur",
    "Amloh",
    "Amritsar",
    "Anandpur Sahib",
    "Badhni Kalan",
    "Bagha Purana",
    "Bakloh",
    "Balachor",
    "Banga",
    "Banur",
    "Barnala",
    "Batala",
    "Begowal",
    "Bhadaur",
    "Bhatinda",
    "Bhawanigarh",
    "Bhikhi",
    "Bhogpur",
    "Bholath",
    "Budhlada",
    "Chima",
    "Dasuya",
    "Dera Baba Nanak",
    "Dera Bassi",
    "Dhanaula",
    "Dhariwal",
    "Dhilwan",
    "Dhudi",
    "Dhuri",
    "Dina Nagar",
    "Dirba",
    "Doraha",
    "Faridkot",
    "Fatehgarh Churian",
    "Fatehgarh Sahib",
    "Fazilka",
    "Firozpur",
    "Firozpur District",
    "Gardhiwala",
    "Garhshankar",
    "Ghanaur",
    "Giddarbaha",
    "Gurdaspur",
    "Guru Har Sahai",
    "Hajipur",
    "Hariana",
    "Hoshiarpur",
    "Ishanpur",
    "Jagraon",
    "Jaito",
    "Jalalabad",
    "Jalandhar",
    "Jandiala",
    "Jandiala Guru",
    "Kalanaur",
    "Kapurthala",
    "Kartarpur",
    "Khamanon",
    "Khanna",
    "Kharar",
    "Khemkaran",
    "Kot Isa Khan",
    "Kotkapura",
    "Laungowal",
    "Ludhiana",
    "Machhiwara",
    "Majitha",
    "Makhu",
    "Malaut",
    "Malerkotla",
    "Mansa",
    "Maur Mandi",
    "Moga",
    "Mohali",
    "Morinda",
    "Mukerian",
    "Nabha",
    "Nakodar",
    "Nangal",
    "Nawanshahr",
    "Nurmahal",
    "Nurpur Kalan",
    "Pathankot",
    "Patiala",
    "Patti",
    "Phagwara",
    "Phillaur",
    "Qadian",
    "Rahon",
    "Raikot",
    "Rajasansi",
    "Rajpura",
    "Ram Das",
    "Rampura",
    "Rupnagar",
    "Samrala",
    "Sanaur",
    "Sangrur",
    "Sardulgarh",
    "Shahid Bhagat Singh Nagar",
    "Shahkot",
    "Sham Churasi",
    "Sirhind-Fategarh",
    "Sri Muktsar Sahib",
    "Sultanpur Lodhi",
    "Sunam",
    "Talwandi Bhai",
    "Talwara",
    "Tarn Taran Sahib",
    "Zira"
]

export const Odisha = [
    "Angul",
    "Angul District",
    "asika",
    "athagarh",
    "Bada Barabil",
    "Balangir",
    "Balasore",
    "Baleshwar",
    "Balimila",
    "Balugaon",
    "Banapur",
    "Banki",
    "Banposh",
    "Baragarh",
    "Barbil",
    "Bargarh",
    "Barpali",
    "Basudebpur",
    "Baud",
    "Baudh",
    "Belaguntha",
    "Bhadrak",
    "Bhadrakh",
    "Bhanjanagar",
    "Bhawanipatna",
    "Bhuban",
    "Bhubaneshwar",
    "Binka",
    "Birmitrapur",
    "Bolanikhodan",
    "Brahmapur",
    "Brajarajnagar",
    "Buguda",
    "Burla",
    "Champua",
    "Chandbali",
    "Chatrapur",
    "Chikitigarh",
    "Chittarkonda",
    "Cuttack",
    "Daitari",
    "Deogarh",
    "Dhenkanal",
    "Digapahandi",
    "Gajapati",
    "Ganjam",
    "Gopalpur",
    "Gudari",
    "Gunupur",
    "Hinjilikatu",
    "Hirakud",
    "Jagatsinghapur",
    "Jagatsinghpur",
    "Jajpur",
    "Jaleshwar",
    "Jatani",
    "Jeypore",
    "Jharsuguda",
    "Jharsuguda District",
    "Kaintragarh",
    "Kalahandi",
    "Kamakhyanagar",
    "Kandhamal",
    "Kantabanji",
    "Kantilo",
    "Kendrapara",
    "Kendraparha",
    "Kendujhar",
    "Kesinga",
    "Khallikot",
    "Kharhial",
    "Khordha",
    "Khurda",
    "Kiri Buru",
    "Kodala",
    "Konarka",
    "Koraput",
    "Kuchaiburi",
    "Kuchinda",
    "Malakanagiri",
    "Malkangiri",
    "Mayūrbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nayagarh District",
    "Nilgiri",
    "Nimaparha",
    "Nowrangapur",
    "Nuapada",
    "Padampur",
    "Paradip Garh",
    "Patamundai",
    "Patnagarh",
    "Phulbani",
    "Pipili",
    "Polasara",
    "Puri",
    "Purushottampur",
    "Rambha",
    "Raurkela",
    "Rayagada",
    "Remuna",
    "Rengali",
    "Sambalpur",
    "Sonepur",
    "Sorada",
    "Soro",
    "Subarnapur",
    "Sundargarh",
    "Talcher",
    "Tarabha",
    "Titlagarh",
    "Udayagiri"
]

export const Nagaland = [
    "Other",
    "Kohima",
    "Phek",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Longleng",
    "Kiphire",
    "Peren",
    "Mokokchūng",
    "Tuensang District",
];
